### ISSUE TITLE
Cannot find module 'commander' after update to 4.3.0

### ISSUE THREAD

**Issue by askovi** [oznu/homebridge-config-ui-x#285]
I am running homebridge on your latest docker image for raspberry pi and I have config-ui-x enabled. It was working fine on 4.2.0 and I just updated to 4.3.0 from the UI and it prompted successful update and restart required. After I clicked restart it never came back online and in the logs I get this:
![configuierror](https://user-images.githubusercontent.com/3981552/57243107-45d04280-7003-11e9-8950-48367f2a0c0e.PNG)

**Comment by oznu** [comment]
Hi @askovi 

Please give the latest version a go. Some changes were made to try and reduce installation errors.

```
# cleanup
sudo npm uninstall -g homebridge-config-ui-x@latest

# reinstall
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by askovi** [comment]
I tried the following:
1. Rebuilt docker container from oznu/homebridge:raspberry-pi which comes with config-ui-x 4.2.0 then I updated to 4.4.0 from the UI and I got the exact same errors as above.
2. I ran docker exec homebridge_homebridge_1 npm uninstall homebridge-config-ui-x@latest then docker exec homebridge_homebridge_1 npm install --unsafe-perm homebridge-config-ui-x@latest 
It installed the new version but it's still just spamming this in the logs

> s6-applyuidgid: fatal: unable to exec homebridge-config-ui-x: No such file or directory

**Comment by askovi** [comment]
I also just tried to make my own docker image and adding 4.4.0 to it and it works fine. So the error only happens when updating.

**Comment by askovi** [comment]
I figured it out. If anybody runs into this issue while running in Standalone Mode on docker, make sure you have the Config block added in platforms[] in your config.json and that sudo is enabled. Even though in standalone mode the config block is not needed for regular use, apparently without it updating has issues. Maybe @oznu can have a look at it.
