### ISSUE TITLE
[Regression] LightBulb Modal not displayed if Lightbulb has Hue/Saturation/Temperature, but no adaptive lighting

### ISSUE THREAD

**Issue by bi-on** [oznu/homebridge-config-ui-x#2820]
### Describe The Bug

When I define a LightBuild accessory with Hue or Temperature Characteristic, but no adaptive lightning, the modal does not open and the error `e.adaptiveLightingSignal is not a function` is thrown.

This is correct, since the "e" object here has `hasAdaptiveLighting=false` and thus `adaptiveLightingSignal=undefined`.

I assume, the problem was introduced with https://github.com/homebridge/homebridge-config-ui-x/commit/bed40522ade2a97d69e2ed43db60590ac8b09824#diff-fae66d557e38ae548e241bdfcb9a2cbaf964f114ea1d3826ef3d52c39bc3658a where in `lightbulb.manage.component.html` the previous `isAdaptiveLightingEnabled` was replaced by a call to `hasAdaptiveLighting()`

This fails, if `hasAdaptiveLighting=false`, but `lightbulb.manage.component.html` is currently missing tests for it in the `@if (targetHue)`, `@if (targetSaturation)` and `@if (targetColorTemperature)` branches

### Config

```JSON

```

### Homebridge UI Version

v5.23.0

### Homebridge Version

v2.0.2

### Node.js Version

v24.15.0 

### Operating System

macOS

### Environment Info

None

### Raspberry Pi Model

None

**Comment by bwp91** [comment]
Hi @bi-on 

Please could you try the beta version of the UI to see if this has been fixed?

Thanks!

**Comment by bi-on** [comment]
@bwp91 - Great, the modal works again!
