### ISSUE TITLE
Version 4.51.1/4.51.2 does not fix bug and `rebuild` doesn't work

### ISSUE THREAD

**Issue by BastianZim** [oznu/homebridge-config-ui-x#1607]
### Describe The Bug

After the update to 4.51.1, Homebridge UI is not running.
Rebuilding it fails with:

```
username@raspberrypi:~ $ sudo hb-service rebuild
ℹ Rebuilding for Node.js v18.18.2...
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './es6/validate-engines.js'
Require stack:
- /opt/homebridge/lib/node_modules/npm/lib/cli.js
- /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/lib/cli.js:1:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebridge/lib/node_modules/npm/lib/cli.js',
    '/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Node.js v18.18.2
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './es6/validate-engines.js'
Require stack:
- /opt/homebridge/lib/node_modules/npm/lib/cli.js
- /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/lib/cli.js:1:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebridge/lib/node_modules/npm/lib/cli.js',
    '/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Node.js v18.18.2
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
```

I could only fix it by running `sudo apt-get reinstall homebridge` but now the version is downgraded again.

### Logs

```text
[27/10/2023, 14:12:28] [Homebridge UI] Error: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node: cannot open shared object file: No such file or directory
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] Node.js v18.18.2
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] Failed to load node-pty module
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] Follow the steps below to resolve this issue.
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] Trying to rebuild automatically...
[27/10/2023, 14:12:28] [Homebridge UI] [node-pty] Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch
[27/10/2023, 14:12:29] [Homebridge UI] [node-pty] Failed to rebuild npm modules automatically. Manual operation is now required.
[27/10/2023, 14:12:29] [Homebridge UI] [node-pty] From the terminal run this command to rebuild npm modules:

[27/10/2023, 14:12:29] [Homebridge UI] sudo hb-service rebuild

[27/10/2023, 14:12:29] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Node.js global modules rebuild required. See log errors above.
    at main (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:29754:19)
    at 1808 (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:29806:1)
    at __webpack_require__ (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:30138:42)
    at /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:30166:1
    at /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:30272:3
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/main.js:30277:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
```

### Homebridge UI Version

Former: 4.51.1 After rebuild: homebridge-config-ui-x v4.50.6

### Homebridge Version

v1.6.1

### Node.js Version

v18.18.2

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

- [ ] Using Docker?
- [ ] Using Hyper-V?
- [X] Using hb-service?

### Raspberry Pi Model

Raspberry Pi 3 A+

**Comment by galzil** [comment]
Neither does 4.51.2
And we can't update as the Debian OS that we installed with doesn't allow GLIBCXX update

**Comment by MO2k4** [comment]
i could fix this via 

``` bash
sudo hb-service rebuild
```

**Comment by rdeutsch3** [comment]
This seems somewhat related to homebridge/homebridge-syno-spk#138

**Comment by BastianZim** [comment]
Yes, probably the same underlying cause. I just wanted to highlight that `rebuild` is not working. 
I would assume that it is related to the fact that `strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX` is giving me `strings: '/usr/lib/arm-linux-gnueabihf/libstdc++.so.6': No such file`. 
However, some sort of `GLIBCXX` should be installed as `sudo dpkg -l | grep libc6` gives me

```shell
ii  libc6:arm64                          2.31-13+rpt2+rpi1+deb11u7        arm64        GNU C Library: Shared libraries
ii  libc6-dbg:arm64                      2.31-13+rpt2+rpi1+deb11u7        arm64        GNU C Library: detached debugging symbols
ii  libc6-dev:arm64                      2.31-13+rpt2+rpi1+deb11u7        arm64        GNU C Library: Development Libraries and Header Files
```

(But this is beyond my knowledge of RPi)

**Comment by NorthernMan54** [comment]
There are two issues going on

1 - NodeJS 20 update on Operating System Environments that don't support it are failing with a GLIBCXX issue - https://github.com/homebridge/homebridge/issues/3453

2 - After the update to config-ui-x 4.51+, the UI doesn't start and needs to have `sudo hb-service rebuild` run.

Your issue is homebridge/homebridge-config-ui-x#2, and you setup is in limbo as your setup for some reason fails trying to run `sudo hb-service rebuild`

We are working on a beta release that should resolve homebridge/homebridge-config-ui-x#2, you could try the test version of Homebridge-config-ui-x-4.52.0-beta.33

**Comment by BastianZim** [comment]
Thanks for the response – that makes sense.

I have plenty of backups and can access via SSH, so whenever the beta is ready for testing, I'm happy to participate however it is helpful!

**Comment by NorthernMan54** [comment]
The beta is available now - 
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/19808920/216a4a7e-8e5b-48b5-8e12-2f89c578458e)

**Comment by BastianZim** [comment]
Ahh sorry didn't know. Ran the beta and it worked :tada:
My node version is v18.18.2. The UI is at homebridge-config-ui-x v4.52.0-beta.33

**Comment by NorthernMan54** [comment]
Tks very much for confirming

**Comment by BastianZim** [comment]
However, updating node still fails (not sure if that is on purpose):

```shell
homebridge@raspberrypi:/var/lib/homebridge $ hb-service update-node
ℹ Updating Node.js from v18.18.2 to v20.9.0...
ℹ Target: /opt/homebridge
✔ Download complete.
✔ Cleaned up npm at at /opt/homebridge/lib/node_modules/npm
✔ Installed Node.js v20.9.0
ℹ Rebuilding for Node.js v20.9.0...
/bin/sh: 1: npm: not found
/bin/sh: 1: npm: not found
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
```

**Comment by NorthernMan54** [comment]
@BastianZim - What does 

`cat /etc/os-release`

and 

`strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX`

show ?

**Comment by BastianZim** [comment]
```shell
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

and 

`strings: '/usr/lib/arm-linux-gnueabihf/libstdc++.so.6': No such file`


_Note_: This is after the failed update of node.

**Comment by BastianZim** [comment]
Strangely enough, I pulled the plug on my Raspberry Pi as it became unresponsive after updating node and I couldn't even SSH in. When I rebooted it, it started to work fine again and the node version is reported as `v20.9.0`.

Running `hb-service update-node` now gives `ℹ Node.js v20.9.0 already up-to-date.`.

**Comment by NorthernMan54** [comment]
If you run `node -v`, `uname -a` and `npm -v` what does it show, also `getconf GNU_LIBC_VERSION`

```
node -v
v18.18.2

uname -a
Linux sheldon 6.1.0-rpi4-rpi-v8 homebridge/homebridge-config-ui-x#1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux

npm -v
9.8.1

getconf GNU_LIBC_VERSION
glibc 2.36
```

**Comment by BastianZim** [comment]
Over SSH I get:

```shell
node -v
-bash: node: command not found

uname -a
Linux raspberrypi 6.1.21-v8+ homebridge/homebridge-config-ui-x#1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

npm -v
-bash: npm: command not found

getconf GNU_LIBC_VERSION
glibc 2.31
```
---

Via the Homebridge terminal I get:

```shell
node -v
v20.9.0

uname -a
Linux raspberrypi 6.1.21-v8+ homebridge/homebridge-config-ui-x#1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

npm -v
bash: npm: command not found

getconf GNU_LIBC_VERSION
glibc 2.31
```

**Comment by NorthernMan54** [comment]
You could try downgrading node, then updating again

**Comment by NorthernMan54** [comment]
ie `sudo hb-service update-node 18` then `sudo hb-service update-node 20`

**Comment by BastianZim** [comment]
Well, it is running fine. I just had to hard-reboot it. 

I did, however, run those commands and it is giving me the same error:

```shell
user@rpi:~ $ sudo hb-service update-node 18 && sudo hb-service update-node 20 && sudo hb-service rebuild 
ℹ Installing Node.js v18.18.2 over v20.9.0...
ℹ Target: /opt/homebridge
✔ Download complete.
✔ Installed Node.js v18.18.2
ℹ Rebuilding for Node.js v18.18.2...
/bin/sh: 1: npm: not found
/bin/sh: 1: npm: not found
Error: Command failed: npm rebuild --unsafe-perm
✖ ERROR: Failed Operation
⚠ Please restart Homebridge for the changes to take effect.
```
Somehow, I don't have npm and it wasn't installed when I installed homebridge

Note: I am still on v20.9.0

**Comment by NorthernMan54** [comment]
Am thinking that over time something has happened to your setup.   Would it make sense to just rebuild from scratch at some point ?

Are you running the homebridge raspbian image or the homebridge apt package ?

**Comment by BastianZim** [comment]
Yeah, I guess so. I don't really have anything major running on it, so I'll probably do that then.

It's the apt package, as I have a couple of other small things running on it for various things.

What I don't understand is besides installing Cloudflare's warp agent, it's a stock Raspbian image with nothing changed. I wonder what bugged it.

**Comment by NorthernMan54** [comment]
If you just do `sudo apt-get reinstall homebridge` it should reset homebridge back our spring release levels.  Pls do a homebridge archive backup first.

**Comment by BastianZim** [comment]
Ok just ran that. I guess I'll wait until the beta is released or should I test anything else?

**Comment by NorthernMan54** [comment]
You could try the beta and update-node again.  I'm curious if the missing NPM is resolved now

**Comment by BastianZim** [comment]
Ahh ok. It's still the same as in https://github.com/homebridge/homebridge-config-ui-x/issues/1607#issuecomment-1785975083 with no NPM found. 
I have no idea how that can be the case, as I can install plugins in Homebridge, which uses NPM, from what I understand.

**Comment by BastianZim** [comment]
Node update fails with the same error but when I pull the power it shows v20.9.0 after restarting.

**Comment by galzil** [comment]
I've updated the OS manually and that seems to solve the problem. 
I guess a clean install and reconfiguring from a backup is a better solution 

I followed the instructions on these 2 places

https://www.linuxcapable.com/how-to-upgrade-from-debian-10-buster-to-debian-11-bullseye/

https://linuxize.com/post/how-to-upgrade-debian-10-to-debian-11/

**Comment by tekstein** [comment]
> The beta is available now - ![image](https://user-images.githubusercontent.com/19808920/279178645-216a4a7e-8e5b-48b5-8e12-2f89c578458e.png)

I'm having the same issue on Synology NAS. I'll try the beta, but I'm unfamiliar with the beta install process on Synology nas. I've looked in the beta package center and do not see anything. Please advise how I can install the beta.

**Comment by rdeutsch3** [comment]
> > The beta is available now - ![image](https://user-images.githubusercontent.com/19808920/279178645-216a4a7e-8e5b-48b5-8e12-2f89c578458e.png)
> 
> I'm having the same issue on Synology NAS. I'll try the beta, but I'm unfamiliar with the beta install process on Synology nas. I've looked in the beta package center and do not see anything. Please advise how I can install the beta.

I'm having the same issue over on homebridge/homebridge-syno-spk#138.  The beta didn't work for me.  My next step is to install the development tools and see if I can rebuild HB.  That said, the latest Node.js doesn't want to be installed 'Non-standard installation path detected: /volume1/@appstore/Node.js_v18/usr/local'

This feels like it may the the end of the line for native homebridge on my DSM. :(

**Comment by NorthernMan54** [comment]
@BastianZim I took at look at a coupe of my machines, and what your seeing is that the Homebridge APT maintains its own copies/versions of NodeJS and NPM for internal use, and occasionally it leverages the OS installed versions.  And on your RPI, the OS does not NPM installed currently.  This explains the differences between you see in the homebridge terminal vs SSH

You can reinstall npm with the command `sudo apt-get install npm`

**Comment by BastianZim** [comment]
Ahh ok that makes sense. Would it be better for the future then to maybe install that with Homebridge?

**Comment by Spy-1** [comment]
I'm a bit confused and can't find a solution.

Can I safely update to Node 20.X.X with the current Docker image (1.61 - not sdk) with Ubuntu 22.04.3 LTS on my Synology NAS???

**Comment by donavanbecker** [comment]
Are you having the same issues with 4.52.1?

**Comment by bil5962** [comment]
I have the same issues with 4.52.1
